connection MASCAB01B
address 192.168.137.1:1883
clientid MASCAB01B
topic MASCAB01B/# both 0
topic in in 0
topic out out 0
topic config both 0
topic session both 0
topic reboot both 0
remote_username guest
remote_password guest
try_private false
cleansession false
bridge_protocol_version mqttv311
log_type error
